package com.mine.warriorsservermybatisplus.mapper;

import com.mine.warriorsservermybatisplus.entity.SysUser;
import com.baomidou.mybatisplus.mapper.BaseMapper;
import org.apache.ibatis.annotations.Mapper;

/**
 * @description: 【用户】映射器
 * @author: Generated by Mine.Lee
 * @create: 2019-01-15
 * @version: v1.0
 */
@Mapper
public interface SysUserMapper extends BaseMapper<SysUser> {

}
